create extension if not exists pgcrypto;
create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text,
 role text not null default 'staff' check(role in ('admin','staff')),
 created_at timestamptz not null default now()
);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') $$;

create table if not exists public.catalog_items(
 id uuid primary key default gen_random_uuid(), brand text not null, reference text not null, name text not null,
 category text not null default 'General', unit text not null default 'barra', bar_length_m numeric,
 weight_kg_m numeric, dimensions_text text, cost_price numeric not null default 0, sale_price numeric not null default 0,
 active boolean not null default true, source_name text, source_page int, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(brand,reference)
);
create table if not exists public.service_rates(
 id uuid primary key default gen_random_uuid(), service_key text unique not null, label text not null,
 unit text not null default 'm2' check(unit in ('m2','ml','unit')), material_rate numeric not null default 0,
 accessory_rate numeric not null default 0, labor_rate numeric not null default 0, installation_rate numeric not null default 0,
 minimum_charge numeric not null default 0, waste_percent numeric not null default 10, margin_percent numeric not null default 20,
 error_percent numeric not null default 15, auto_quote boolean not null default false, updated_at timestamptz not null default now()
);
insert into public.service_rates(service_key,label,unit,auto_quote) values
 ('window_sliding','Ventana corrediza','m2',false),('door','Puerta','m2',false),('railing','Baranda de vidrio','ml',false),
 ('cover_existing','Cubierta con estructura existente','m2',false),('pergola_full','Pérgola / cubierta completa','m2',false),
 ('shower','Mampara / baño','m2',false),('mirror','Espejo','m2',false),('special','Proyecto especial','unit',false)
on conflict(service_key) do nothing;

create table if not exists public.gallery_projects(
 id uuid primary key default gen_random_uuid(), title text not null, category text not null, description text,
 cover_url text, published boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.leads(
 id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, phone text not null, email text,
 city text not null, sector text, preferred_contact text, project_type text, project_label text, quote_mode text,
 supply_mode text, needs_visit boolean not null default false, risk_level text, assessment jsonb, estimate jsonb, project_items jsonb not null default '[]'::jsonb, conversation jsonb,
 status text not null default 'new' check(status in ('new','reviewing','visit_scheduled','quoted','won','lost')), created_at timestamptz not null default now()
);
create table if not exists public.lead_images(
 id uuid primary key default gen_random_uuid(), lead_id uuid not null references public.leads(id) on delete cascade, storage_path text not null, created_at timestamptz not null default now()
);
create table if not exists public.ai_rate_limits(
 id bigint generated by default as identity primary key, client_hash text not null, created_at timestamptz not null default now()
);
create index if not exists ai_rate_limits_client_time_idx on public.ai_rate_limits(client_hash, created_at desc);
create table if not exists public.ai_usage_log(
 id bigint generated by default as identity primary key, model text, input_tokens int not null default 0, output_tokens int not null default 0,
 scope text, accepted boolean not null default true, created_at timestamptz not null default now()
);
create or replace function public.ai_tokens_today() returns bigint language sql stable security definer set search_path=public as $$
 select coalesce(sum(input_tokens + output_tokens),0)::bigint from public.ai_usage_log where created_at >= date_trunc('day', now())
$$;
create table if not exists public.notification_outbox(
 id bigint generated by default as identity primary key, lead_code text, channel text, status text, payload jsonb, created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;alter table public.catalog_items enable row level security;alter table public.service_rates enable row level security;alter table public.gallery_projects enable row level security;alter table public.leads enable row level security;alter table public.ai_usage_log enable row level security;alter table public.notification_outbox enable row level security;alter table public.lead_images enable row level security;alter table public.ai_rate_limits enable row level security;
create policy "profile self read" on public.profiles for select using(id=auth.uid() or public.is_admin());
create policy "catalog public read" on public.catalog_items for select using(active=true or public.is_admin());
create policy "catalog admin all" on public.catalog_items for all using(public.is_admin()) with check(public.is_admin());
create policy "rates admin read" on public.service_rates for select using(public.is_admin());
create policy "rates admin all" on public.service_rates for all using(public.is_admin()) with check(public.is_admin());
create policy "gallery public read" on public.gallery_projects for select using(published=true or public.is_admin());
create policy "gallery admin all" on public.gallery_projects for all using(public.is_admin()) with check(public.is_admin());
create policy "leads admin" on public.leads for all using(public.is_admin()) with check(public.is_admin());
create policy "usage admin" on public.ai_usage_log for select using(public.is_admin());
create policy "outbox admin" on public.notification_outbox for select using(public.is_admin());
create policy "lead images admin" on public.lead_images for select using(public.is_admin());

insert into storage.buckets(id,name,public) values('gallery','gallery',true) on conflict(id) do update set public=true;
insert into storage.buckets(id,name,public) values('lead-images','lead-images',false) on conflict(id) do update set public=false;
create policy "gallery objects public" on storage.objects for select using(bucket_id='gallery');
create policy "gallery objects admin insert" on storage.objects for insert to authenticated with check(bucket_id='gallery' and public.is_admin());
create policy "gallery objects admin update" on storage.objects for update to authenticated using(bucket_id='gallery' and public.is_admin()) with check(bucket_id='gallery' and public.is_admin());
create policy "gallery objects admin delete" on storage.objects for delete to authenticated using(bucket_id='gallery' and public.is_admin());
